### PR TITLE
json: properly handle dependencies

### PR DESCRIPTION
**Pull request by Rylan12**
This PR allows `brew json` to handle dependencies properly.

When the bottles are all downloaded, they're downloaded directly to `$HOMEBREW_CACHE/downloads/$SHA256--$NAME.$PKG_VERSION.$OS.bottle.tar.gz` (this isn't anything new. They are also symlinked into `$HOMEBREW_CACHE/$NAME--$PKG_VERSION`. This mimics what happens on a typical bottle download, too (run e.g. `brew fetch hello` to see). This PR does have a minor change to get this working (the version needed to be set in the bottle resource).

The way I ended up handling dependencies is by monkey patching the `Formulary::factory` method. Now, when passed a `ref`, it will still go through the normal procedure for finding a formula (e.g. looking it the various taps). The difference is that now, if it can't find a formula, it will also check the files that match `$HOMEBREW_CACHE/$ref--*` and choose the one with the most recent version to use.

Another option that I might like a bit more would be to add a list of the JSON-downloaded-bottles in `Formulary`. `Formulary::factory` can then first check whether `ref` exists in this list and, if so, can go directly to the freshly-downloaded bottle archive without needing to search through the cache files to find the most recent version and hope there are no issues with naming.

Thoughts?

---

Testing this is pretty easy. I recommend using the `rnv` formula as it has a very simple dependency structure:

```console
$ brew deps --tree rnv
rnv
└── expat
```

To test, first delete the `rnv` and `expat` formula files from homebrew/core (you might be able to just untap homebrew/core but I haven't tried this yet), clear the cache if you'd like, and run `brew json rnv`.

You'll notice that the `postinstall` calls don't work, but I believe this will be fixed by https://github.com/Homebrew/brew/pull/11468.

Also, there aren't any `==> Pouring expat--2.4.1.big_sur.bottle.tar.gz` or `==> Pouring rnv--1.7.11.big_sur.bottle.tar.gz` messages, but this will be fixed by https://github.com/Homebrew/brew/pull/11524

### CODE REVIEW

**Review by MikeMcQuaid — APPROVED** [review]
Fine with this from now. If we're going to need something like this in Homebrew/brew eventually I'd be in favour of getting this behaviour in now and e.g. guarded by an undocumented environment variable (`HOMEBREW_...`) which can be set by `brew json` or by developers at download time.

**Comment by Rylan12** [comment]
Do you have a preference for which of the methods above is better?

In terms of adding to brew, what's the benefit of doing it now? I'm definitely not opposed to doing it now if you'd like but since it wouldn't be used anywhere internally, yet, I wonder if we should just wait. I don't think waiting will make incorporating into the future any more difficult.

**Comment by MikeMcQuaid** [comment]
Don't mind waiting, just the monkeypatching is a bit more likely to break.

**Comment by Rylan12** [comment]
Fair enough. I think I will merge for now, though, as iterating on it will be easier while it's in this tap. IN the future if it causes problems we can migrate over. I don't expect anything major, though, as the `Formulary` class seems pretty stable, and (while not a long-term solution) I follow Homebrew/brew pretty closely so I'm more likely to notice breaking changes.

**Comment by Rylan12** [comment]
Actually, I'd like to try the other method of dependency handling first to see if I like that better

**Comment by Rylan12** [comment]
Nope, changes my mind again. I'm going to merge and then I'll try changing in a separate PR

**Pull request merged**
